# Generated by Django 6.0.2 on 2026-02-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialupload',
            name='business_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialupload',
            name='gstin',
            field=models.CharField(default='N/A', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialupload',
            name='pan',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
    ]
