# Generated by Django 6.0.2 on 2026-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "uploads",
            "0002_financialupload_business_name_financialupload_gstin_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RawTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameOrig", models.CharField(db_index=True, max_length=100)),
                ("date", models.DateTimeField()),
                ("txn_type", models.CharField(max_length=50)),
                ("amount", models.FloatField()),
                ("nameDest", models.CharField(blank=True, max_length=100, null=True)),
                ("balance", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="financialupload",
            name="business_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="financialupload",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
