# Generated by Django 6.0.2 on 2026-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0003_rawtransaction_alter_financialupload_business_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyCreditProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200, unique=True)),
                ("ml_features", models.JSONField()),
                ("credit_score", models.IntegerField(blank=True, null=True)),
                ("decision", models.CharField(blank=True, max_length=50, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
