# Generated by Django 6.0.2 on 2026-02-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_companycreditprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companycreditprofile",
            name="explanation",
        ),
        migrations.AddField(
            model_name="companycreditprofile",
            name="probability_of_default",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companycreditprofile",
            name="risk_bucket",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companycreditprofile",
            name="top_risk_drivers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companycreditprofile",
            name="ml_features",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
