# Generated by Django 6.0.2 on 2026-02-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0005_remove_companycreditprofile_explanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycreditprofile",
            name="decision_threshold",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
